Repository ita-social-projects/SpaceToStudy-Packages, pull requests merged in 2025-05, with the labels that each got.

#33 Implement theme as package
  .storybook/preview.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  packages/components/dist/components.esm.js
  packages/components/dist/components.esm.js.LICENSE.txt
  packages/components/lib/components.ts
  packages/styles/lib/styles.scss
  packages/styles/lib/theme.scss
  packages/theme/dist/index.scss
  packages/theme/dist/theme.d.mts
  packages/theme/dist/theme.mjs
  packages/theme/lib/Button/app.button.ts
  packages/theme/lib/Checkbox/app.checkbox.ts
  packages/theme/lib/Custom-animations/custom-animations.ts
  packages/theme/lib/Custom-scrollbar/custom-scrollbar.ts
  packages/theme/lib/Custom-shadows/custom-shadows.ts
  packages/theme/lib/MenuItem/app.menu-item.ts
  packages/theme/lib/MenuList/app.menu-list.ts
  packages/theme/lib/Pallete/app.pallete.ts
  packages/theme/lib/Select/app.select.ts
  packages/theme/lib/SvgIcon/app.svgicon.ts
  packages/theme/lib/Table/app.table.ts
  packages/theme/lib/TextField/app.textfield.ts
  packages/theme/lib/Tooltip/app.tooltip.ts
  packages/theme/lib/Typography/app.typography.ts
  packages/theme/lib/custom-mui.styles.ts
  packages/theme/lib/index.scss
  packages/theme/lib/theme.ts
  packages/theme/package.json
  packages/theme/tsconfig.json
  webpack.config.ts
Labels: question, feature, package

#41 Updated gitignore
  .gitignore
  .storybook/preview.tsx
  packages/components/dist/components.esm.js
  packages/components/dist/components.esm.js.LICENSE.txt
  packages/theme/dist/index.scss
  packages/theme/dist/theme.d.mts
  packages/theme/dist/theme.mjs
Labels: enhancement, feature

#36 created tooltip component
  .storybook/main.ts
  packages/components/__tests__/Tooltip.spec.jsx
  packages/components/lib/Tooltip/Tooltip.scss
  packages/components/lib/Tooltip/Tooltip.stories.tsx
  packages/components/lib/Tooltip/Tooltip.tsx
  packages/components/types/components/lib/Tooltip/Tooltip.d.ts
  packages/components/types/components/lib/Tooltip/Tooltip.stories.d.ts
  packages/components/types/utils/__tests__/cn.spec.d.ts
Labels: enhancement, feature

#25 Implement "IconButton" component
  package-lock.json
  package.json
  packages/components/__tests__/IconButton.spec.jsx
  packages/components/lib/IconButton/IconButton.scss
  packages/components/lib/IconButton/IconButton.stories.tsx
  packages/components/lib/IconButton/IconButton.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/IconButton/IconButton.d.ts
  packages/components/types/components/lib/IconButton/IconButton.stories.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature

#28 Implement "MenuItem" component
  packages/components/__tests__/MenuItem.spec.jsx
  packages/components/lib/MenuItem/MenuItem.constants.ts
  packages/components/lib/MenuItem/MenuItem.scss
  packages/components/lib/MenuItem/MenuItem.stories.tsx
  packages/components/lib/MenuItem/MenuItem.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/MenuItem/MenuItem.constants.d.ts
  packages/components/types/components/lib/MenuItem/MenuItem.d.ts
  packages/components/types/components/lib/MenuItem/MenuItem.stories.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature

#31 Implement "Menu" component
  packages/components/__tests__/Menu.spec.jsx
  packages/components/__tests__/MenuItem.spec.jsx
  packages/components/lib/Menu/Menu.scss
  packages/components/lib/Menu/Menu.stories.tsx
  packages/components/lib/Menu/Menu.tsx
  packages/components/lib/MenuItem/MenuItem.scss
  packages/components/lib/MenuItem/MenuItem.stories.tsx
  packages/components/lib/MenuItem/MenuItem.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/Menu/Menu.d.ts
  packages/components/types/components/lib/Menu/Menu.stories.d.ts
  packages/components/types/components/lib/MenuItem/MenuItem.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: duplicate, feature

#30 Implement "Badge" component
  packages/components/__tests__/Badge.spec.jsx
  packages/components/lib/Badge/Badge.scss
  packages/components/lib/Badge/Badge.stories.tsx
  packages/components/lib/Badge/Badge.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/Badge/Badge.d.ts
  packages/components/types/components/lib/Badge/Badge.stories.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature

#39 Implement 'Chip' component #11
  packages/components/__tests__/Chip.spec.jsx
  packages/components/lib/Chip/Chip.scss
  packages/components/lib/Chip/Chip.stories.tsx
  packages/components/lib/Chip/Chip.tsx
  packages/components/lib/Chip/Chip.types.ts
  packages/components/lib/Chip/ChipInternalComponent.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/Chip/Chip.d.ts
  packages/components/types/components/lib/Chip/Chip.stories.d.ts
  packages/components/types/components/lib/Chip/Chip.types.d.ts
  packages/components/types/components/lib/Chip/ChipInternalComponent.d.ts
  packages/components/types/components/lib/Chip/types.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature

#34 Implemented Input Field component
  packages/components/__tests__/InputField.spec.jsx
  packages/components/lib/InputField/InputField.constants.ts
  packages/components/lib/InputField/InputField.scss
  packages/components/lib/InputField/InputField.stories.tsx
  packages/components/lib/InputField/InputField.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/InputField/InputField.constants.d.ts
  packages/components/types/components/lib/InputField/InputField.d.ts
  packages/components/types/components/lib/InputField/InputField.stories.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature

#37 Implement "Divider" component
  packages/components/__tests__/Divider.spec.jsx
  packages/components/lib/Divider/Divider.scss
  packages/components/lib/Divider/Divider.stories.tsx
  packages/components/lib/Divider/Divider.tsx
  packages/components/lib/components.ts
  packages/components/types/components/lib/Divider/Divider.d.ts
  packages/components/types/components/lib/Divider/Divider.stories.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature

#42 Fix tests for 'Badge' component
  packages/components/__tests__/Badge.spec.jsx
Labels: bug

#29 Implemented LinkButton component
  package-lock.json
  packages/components/__tests__/LinkButton.spec.jsx
  packages/components/lib/LinkButton/LinkButton.scss
  packages/components/lib/LinkButton/LinkButton.stories.tsx
  packages/components/lib/LinkButton/LinkButton.tsx
  packages/components/lib/components.ts
  packages/components/package.json
  packages/components/types/components/lib/LinkButton/LinkButton.d.ts
  packages/components/types/components/lib/LinkButton/LinkButton.stories.d.ts
  packages/components/types/components/lib/components.d.ts
Labels: feature
